node('master'){
  def jenkins

  stage('Pull jenkins repo') {
    /* Pull jenkins docker builder git repo */

    checkout scm

  }

  stage('Build jenkins image') {
    /* Build jenkins docker image */

    jenkins = docker.build("cchen1103/jenkins")

  }

  stage('Test jenkins image') {
    /* Launch jenkins */

    jenkins.withRun('-v /var/run/docker.sock:/var/run/docker.sock') { c ->
      docker.image('alpine').inside("--link ${c.id}:jenkins --user=root") {

        sh 'apk --update add curl'
        sh 'curl http://jenkins:8080'

      }
    }

  }

  stage('Push jenkins image') {
    /* Push jenkins image to dockerhub */

    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
      jenkins.push("${env.BUILD_NUMBER}")
      jenkins.push("latest")
    }

  }
}
